export const exercises = [
  {
    day: 1,
    title: "Plank Hold",
    duration: 60,
    description: "Hold a perfect forearm plank. Keep your glutes squeezed, shoulders stacked, and your belly button pulled tight toward your spine.",
  },
  {
    day: 2,
    title: "Air Squats",
    duration: 60,
    description: "Drop into deep bodyweight squats as smoothly and quickly as possible. Keep your weight in your heels and chest up.",
  },
  {
    day: 3,
    title: "Dead Bug",
    duration: 60,
    description: "Lie on your back with arms up and knees bent at 90 degrees. Alternately lower the opposite arm and leg, keeping your lower back flat.",
  },
  {
    day: 4,
    title: "Push-Up Hold",
    duration: 60,
    description: "Lower halfway down into a push-up and hold that position statically, or alternate between a high plank and low plank position.",
  },
  {
    day: 5,
    title: "High Knees",
    duration: 60,
    description: "Run in place at high intensity, driving your knees up to hip height as rapidly as possible to spike your heart rate.",
  },
  {
    day: 6,
    title: "Superman Hold",
    duration: 60,
    description: "Lie face down on your belly and lift your chest, arms, and legs off the floor simultaneously to strengthen your posterior chain.",
  },
  {
    day: 7,
    title: "Deep Squat Hold",
    duration: 60,
    description: "Drop to the absolute bottom of a squat and hold it. Shift your weight slightly side to side to open up tight hips and ankles.",
  },
  {
    day: 8,
    title: "Mountain Climbers",
    duration: 60,
    description: "From a push-up position, rapidly drive your knees toward your chest in an alternating, running motion.",
  },
  {
    day: 9,
    title: "Glute Bridge Pulsing",
    duration: 60,
    description: "Lie on your back, drive your hips up to the ceiling, and continuously pulse up and down at the very top inch of the movement.",
  },
  {
    day: 10,
    title: "Side Plank (Left)",
    duration: 60,
    description: "Prop yourself up on your left elbow and side of your foot. Hold a perfectly straight line from head to heels to target the obliques.",
  },
  {
    day: 11,
    title: "Side Plank (Right)",
    duration: 60,
    description: "Prop yourself up on your right elbow and side of your foot. Keep your hips raised high and core tight for the full minute.",
  },
  {
    day: 12,
    title: "Reverse Lunges",
    duration: 60,
    description: "Step backward into a lunge, alternating legs. Ensure your front knee stays aligned over your ankle and your torso stays upright.",
  },
  {
    day: 13,
    title: "Jumping Jacks",
    duration: 60,
    description: "Perform classic jumping jacks with full range of motion in your arms and legs to get your blood flowing instantly.",
  },
  {
    day: 14,
    title: "Wall Sit",
    duration: 60,
    description: "Press your back flat against a wall and lower your hips until your thighs are parallel to the floor, holding at a 90-degree angle.",
  },
  {
    day: 15,
    title: "Burpees",
    duration: 60,
    description: "Drop to a push-up position, touch your chest to the floor, jump your feet back in, and explode upward with a jump.",
  },
  {
    day: 16,
    title: "Bicycle Crunches",
    duration: 60,
    description: "Lie on your back and perform fast, rotational core work by touching your alternating elbows to the opposite knees.",
  },
  {
    day: 17,
    title: "Inchworms",
    duration: 60,
    description: "Start standing, hinge at the hips to touch the floor, walk your hands out to a high plank, then walk your feet back up to your hands.",
  },
  {
    day: 18,
    title: "Skater Hops",
    duration: 60,
    description: "Leap laterally side-to-side from one foot to the other, landing softly with bent knees to build power and ankle stability.",
  },
  {
    day: 19,
    title: "Bear Crawl Hold",
    duration: 60,
    description: "Get on all fours with hands under shoulders, then hover your knees exactly one inch off the ground. Hold still and engage your core.",
  },
  {
    day: 20,
    title: "Calf Raises",
    duration: 60,
    description: "Pump out continuous calf raises. Explode up onto your tiptoes, squeeze at the peak, and lower down slowly under control.",
  },
  {
    day: 21,
    title: "Bird-Dog",
    duration: 60,
    description: "On all fours, simultaneously extend your opposite arm and leg straight out. Hold for 2 seconds to stabilize your spine, then switch.",
  },
  {
    day: 22,
    title: "Jump Squats",
    duration: 60,
    description: "Drop down into a standard squat and explode upward vertically as high as possible. Focus on landing softly on your feet.",
  },
  {
    day: 23,
    title: "Hollow Body Hold",
    duration: 60,
    description: "Lie on your back, press your lower back completely flat into the ground, and lift your arms and feet slightly off the floor.",
  },
  {
    day: 24,
    title: "Pike Push-Ups",
    duration: 60,
    description: "Pike your hips high into an inverted V-shape. Lower the top of your head toward the floor between your hands to target the shoulders.",
  },
  {
    day: 25,
    title: "Flutter Kicks",
    duration: 60,
    description: "Lie on your back with your hands under your hips. Lift your feet slightly and rapidly flutter them up and down without bending your knees.",
  },
  {
    day: 26,
    title: "Crab Walk",
    duration: 60,
    description: "Sit on the floor, lift your hips high with hands and feet planted, and walk around to open up your chest, shoulders, and hips.",
  },
  {
    day: 27,
    title: "Shadow Boxing",
    duration: 60,
    description: "Bounce lightly on your toes and throw rapid, non-stop punches into the air with snappy extension and full rotation.",
  },
  {
    day: 28,
    title: "Russian Twists",
    duration: 60,
    description: "Balance on your tailbone with feet elevated, and rotate your torso side to side as quickly as you can while maintaining stability.",
  },
  {
    day: 29,
    title: "Thrusters",
    duration: 60,
    description: "Grab two objects (like water bottles), drop into a full deep squat, and explode upward, driving the weights overhead as you stand.",
  },
  {
    day: 30,
    title: "Push-Up Benchmark",
    duration: 60,
    description: "Perform as many consecutive, clean, full-range push-ups as you can before the 60-second timer runs out to test your progress.",
  },
];